/*--------------*/
/*Carga de Temas*/
/*--------------*/

INSERT INTO Temas VALUES ('Generador de Productos (Parametría)',1)
INSERT INTO Temas VALUES ('Cuentas Corrientes Cajas de Ahorro',2)
INSERT INTO Temas VALUES ('Créditos',3)
INSERT INTO Temas VALUES ('Plazos Fijos',4)
INSERT INTO Temas VALUES ('Ingresos y Egresos Varios',5)
INSERT INTO Temas VALUES ('Garantía',6)
INSERT INTO Temas VALUES ('Generales – Dependen de Parametria de Producto',7)
INSERT INTO Temas VALUES ('Contabilidad',8)
INSERT INTO Temas VALUES ('BCRA',9)
INSERT INTO Temas VALUES ('Generador de notas',10)
INSERT INTO Temas VALUES ('Ingresos Masivos',11)
INSERT INTO Temas VALUES ('H2H',12)
INSERT INTO Temas VALUES ('Seguridad',13)
INSERT INTO Temas VALUES ('Anses',14)
INSERT INTO Temas VALUES ('Clientes',15)
INSERT INTO Temas VALUES ('Generador de Transacciones',16)
INSERT INTO Temas VALUES ('Caja y Tesorería',17)
INSERT INTO Temas VALUES ('Generador de Planilla',18)
INSERT INTO Temas VALUES ('Financiera Minorista',19)
INSERT INTO Temas VALUES ('Impuesto (cada impuestos incluye Parametrización, Rendición, Devolución, y Proceso de Calculo)',20)
INSERT INTO Temas VALUES ('Cuentas Judiciales',21)
INSERT INTO Temas VALUES ('Financiera Mayorista',22)
INSERT INTO Temas VALUES ('Gestión de Cobranza',23)
INSERT INTO Temas VALUES ('Riesgo Crediticio',24)
INSERT INTO Temas VALUES ('Control de Gestión',25)
INSERT INTO Temas VALUES ('Servicios',26)
INSERT INTO Temas VALUES ('Cambio',27)
INSERT INTO Temas VALUES ('Tarjetas Débito',28)
INSERT INTO Temas VALUES ('Giros y Transferencias',29)
INSERT INTO Temas VALUES ('Débitos Directos',30)
INSERT INTO Temas VALUES ('NIIF',31)
INSERT INTO Temas VALUES ('UVA',32)
INSERT INTO Temas VALUES ('Multihilo',33)
INSERT INTO Temas VALUES ('Tarjeta de Credito',34)
INSERT INTO Temas VALUES ('Agente 7x24 - Bot',35)
INSERT INTO Temas VALUES ('Report Server',36)
INSERT INTO Temas VALUES ('Capacitaciones',37)
INSERT INTO Temas VALUES ('Herramientas para Servicios Apis (sólo para el área herramientas)',38)
INSERT INTO Temas VALUES ('Otras herramientas',39)

/*------------------*/
/*Carga de Subtemas */
/*------------------*/

INSERT INTO Subtemas VALUES ('Proceso-Tarea',102,1)
INSERT INTO Subtemas VALUES ('Administración Formas de Administración',103,1)
INSERT INTO Subtemas VALUES ('Administración Cargos Financieros',104,1)
INSERT INTO Subtemas VALUES ('Administración Historias',105,1)
INSERT INTO Subtemas VALUES ('Rutinas de Cálculo ',106,1)
INSERT INTO Subtemas VALUES ('Devengamiento',107,1)
INSERT INTO Subtemas VALUES ('Ajuste de Cartera',108,1)
INSERT INTO Subtemas VALUES ('Administración de Pizarras',109,1)
INSERT INTO Subtemas VALUES ('Administración de Cheques',10,2)
INSERT INTO Subtemas VALUES ('Funciones. Transacciones de Cheque',11,2)
INSERT INTO Subtemas VALUES ('Liquidación de intereses Acr/Deu',12,2)
INSERT INTO Subtemas VALUES ('Adm y Calc de Interes sobre Acuerdos',13,2)
INSERT INTO Subtemas VALUES ('Funciones Déb./Cred/Com',14,2)
INSERT INTO Subtemas VALUES ('Capitalización de Interés',15,2)
INSERT INTO Subtemas VALUES ('Cobro de Comisiones Mensuales',16,2)
INSERT INTO Subtemas VALUES ('Impuestos',17,2)
INSERT INTO Subtemas VALUES ('Resumen de Ctas',18,2)
INSERT INTO Subtemas VALUES ('Cierre de Cuentas',19,2)
INSERT INTO Subtemas VALUES ('Armado de Saldos',20,2)
INSERT INTO Subtemas VALUES ('Inmovilización y Bloqueo de Cuentas',21,2)
INSERT INTO Subtemas VALUES ('Emisión de Comprobantes',22,2)
INSERT INTO Subtemas VALUES ('Déb. Pendientes',23,2)
INSERT INTO Subtemas VALUES ('Campañas de Bonificación de Comisiones',24,2)
INSERT INTO Subtemas VALUES ('Generación de Resúmenes Masivos',25,2)
INSERT INTO Subtemas VALUES ('Envio de resumen por Mail',26,2)
INSERT INTO Subtemas VALUES ('Echeq Configuracion',27,2)
INSERT INTO Subtemas VALUES ('Echeq emisión',28,2)
INSERT INTO Subtemas VALUES ('Echeq depósito',29,2)
INSERT INTO Subtemas VALUES ('Echeq negociación',30,2)
INSERT INTO Subtemas VALUES ('Echeq CAC (Certif . Accion Civil)',31,2)
INSERT INTO Subtemas VALUES ('Debín/Credín.',32,2)
INSERT INTO Subtemas VALUES ('Acuerdos en CC',33,2)
INSERT INTO Subtemas VALUES ('Echeq Pago y depósito por Ventanilla',34,2)
INSERT INTO Subtemas VALUES ('Echeq Devolución',35,2)
INSERT INTO Subtemas VALUES ('Echeq Cesion Electrónica de Derechos (CED)',36,2)
INSERT INTO Subtemas VALUES ('Camara recibida vuelco CP0',37,2)
INSERT INTO Subtemas VALUES ('Servicios de novedades de echeq (Depósito, Custodia Rescate y Emision)',38,2)
INSERT INTO Subtemas VALUES ('Sirplus - circuito de cuentas de recaudacion de pagos',39,2)
INSERT INTO Subtemas VALUES ('Api Debito/Credito con control de duplicidad',40,2)
INSERT INTO Subtemas VALUES ('CEDIP Banco receptor',41,2)
INSERT INTO Subtemas VALUES ('Liquidación',42,3)
INSERT INTO Subtemas VALUES ('Funciones Pagos/Anulación/Cancelación',43,3)
INSERT INTO Subtemas VALUES ('Scoring Versión BSE',44,3)
INSERT INTO Subtemas VALUES ('Informe de Deuda',45,3)
INSERT INTO Subtemas VALUES ('Refinanciación',46,3)
INSERT INTO Subtemas VALUES ('Restructuración',47,3)
INSERT INTO Subtemas VALUES ('Pase a Legales',48,3)
INSERT INTO Subtemas VALUES ('Descuentos de Cuotas',49,3)
INSERT INTO Subtemas VALUES ('Cobro cuotas en base a Acreditacion de Sueldo',50,3)
INSERT INTO Subtemas VALUES ('Lote de reserva para el cobro de cuotas',51,3)
INSERT INTO Subtemas VALUES ('Venta de Cartera',52,3)
INSERT INTO Subtemas VALUES ('Seguro',53,3)
INSERT INTO Subtemas VALUES ('Pase a Irrecuperables',54,3)
INSERT INTO Subtemas VALUES ('Ajuste Unitario de Cartera',55,3)
INSERT INTO Subtemas VALUES ('Compra de Cartera',56,3)
INSERT INTO Subtemas VALUES ('Leasing',57,3)
INSERT INTO Subtemas VALUES ('Bonificaciones de Gastos de Liquidación y Circuito de autorización',58,3)
INSERT INTO Subtemas VALUES ('Scoring por Plataforma',59,3)
INSERT INTO Subtemas VALUES ('Subsidios',60,3)
INSERT INTO Subtemas VALUES ('Administración de Cupos para CR',61,3)
INSERT INTO Subtemas VALUES ('Acuerdos en CR',62,3)
INSERT INTO Subtemas VALUES ('MIPYME',63,3)
INSERT INTO Subtemas VALUES ('Liquidacion de créditos (Ventana)',64,3)
INSERT INTO Subtemas VALUES ('Pase a quiebra',65,3)
INSERT INTO Subtemas VALUES ('Parametrización de Tramos',66,4)
INSERT INTO Subtemas VALUES ('Liquidación',67,4)
INSERT INTO Subtemas VALUES ('Renovación',68,4)
INSERT INTO Subtemas VALUES ('Funciones. Pagos/Anulación/Cancelación',69,4)
INSERT INTO Subtemas VALUES ('Plazos Fijos UVA',70,4)
INSERT INTO Subtemas VALUES ('Administración Entes - Convenios',71,5)
INSERT INTO Subtemas VALUES ('Funciones. Transacciones',72,5)
INSERT INTO Subtemas VALUES ('Recaudación – Punta de Caja',73,5)
INSERT INTO Subtemas VALUES ('Parametrización Tipos/subtipos',74,6)
INSERT INTO Subtemas VALUES ('Administración de garantías',75,6)
INSERT INTO Subtemas VALUES ('Contabilización de garantías',76,6)
INSERT INTO Subtemas VALUES ('Funciones. Transacciones',77,6)
INSERT INTO Subtemas VALUES ('Circuito de Garantías de Mercedes Benz',78,6)
INSERT INTO Subtemas VALUES ('Inventario de Garantias – Ver dif Mercedes',79,6)
INSERT INTO Subtemas VALUES ('Proceso de Calculo Consumo de Garantia del BCRA',80,6)
INSERT INTO Subtemas VALUES ('Autorización de de Garantías Cotización y Asignacion de Garantías a operaciones',81,6)
INSERT INTO Subtemas VALUES ('Ajuste de Cartera',82,7)
INSERT INTO Subtemas VALUES ('Calculo de Índices de Ajuste (CER-CVS – UVA)',83,7)
INSERT INTO Subtemas VALUES ('Rutinas de Amortización',84,7)
INSERT INTO Subtemas VALUES ('Calculo de IVA',85,7)
INSERT INTO Subtemas VALUES ('Ejecución de Proceso de tareas',86,7)
INSERT INTO Subtemas VALUES ('Congelamiento',87,7)
INSERT INTO Subtemas VALUES ('Ajuste de Cartera',82,8)
INSERT INTO Subtemas VALUES ('Calculo de Índices de Ajuste (CER-CVS – UVA)',83,8)
INSERT INTO Subtemas VALUES ('Rutinas de Amortización',84,8)
INSERT INTO Subtemas VALUES ('Calculo de IVA',85,8)
INSERT INTO Subtemas VALUES ('Ejecución de Proceso de tareas',86,8)
INSERT INTO Subtemas VALUES ('Congelamiento',87,8)
INSERT INTO Subtemas VALUES ('Plan de Cuentas',88,8)
INSERT INTO Subtemas VALUES ('Generación de Minutas Libres y Predefinidas',89,8)
INSERT INTO Subtemas VALUES ('Consultas y Modificación de Minutas',90,8)
INSERT INTO Subtemas VALUES ('Circuito de Autorización de Minutas',91,8)
INSERT INTO Subtemas VALUES ('Balances',92,8)
INSERT INTO Subtemas VALUES ('Mayores / Subdiarios',93,8)
INSERT INTO Subtemas VALUES ('Contabilidad Automática',94,8)
INSERT INTO Subtemas VALUES ('Sobregiro',95,8)
INSERT INTO Subtemas VALUES ('Revalúo',96,8)
INSERT INTO Subtemas VALUES ('Mayorización',97,8)
INSERT INTO Subtemas VALUES ('Administración de Libros contables – NIIF',98,8)
INSERT INTO Subtemas VALUES ('Vuelco de Minutas de sistemas externos',99,8)
INSERT INTO Subtemas VALUES ('Inicio y Cierre de día contable',100,8)
INSERT INTO Subtemas VALUES ('Cierre de Mes y Diario Rubricado',101,8)
INSERT INTO Subtemas VALUES ('Conciliación Automática de Cartera y Contabilidad',102,8)
INSERT INTO Subtemas VALUES ('Ajuste por Inflacion proceso',103,8)
INSERT INTO Subtemas VALUES ('Ajuste por inflacion Configuracion a nivel de rubros',104,8)
INSERT INTO Subtemas VALUES ('Balance',105,9)
INSERT INTO Subtemas VALUES ('Requisitos Mínimos de Liquidez - RML',106,9)
INSERT INTO Subtemas VALUES ('Efectivo Mínimo',107,9)
INSERT INTO Subtemas VALUES ('Aplicacion de Recursos',108,9)
INSERT INTO Subtemas VALUES ('Deudores Sist. Fin.',109,9)
INSERT INTO Subtemas VALUES ('Posición de Liquidez',110,9)
INSERT INTO Subtemas VALUES ('Capitales Mínimos',111,9)
INSERT INTO Subtemas VALUES ('Estado de Situación de Deudores',112,9)
INSERT INTO Subtemas VALUES ('Tipos de Cartera',113,9)
INSERT INTO Subtemas VALUES ('Riesgo de Tasa Operacional',114,9)
INSERT INTO Subtemas VALUES ('Riesgo de Tasa Contable',115,9)
INSERT INTO Subtemas VALUES ('Riesgo Financiero',116,9)
INSERT INTO Subtemas VALUES ('RPC Banco',117,9)
INSERT INTO Subtemas VALUES ('Deudas por Actividades - 3212 - SIN USO 2024',118,9)
INSERT INTO Subtemas VALUES ('Estadísticas de Plazos Fijos - B 5961 - SIN USO 2024',119,9)
INSERT INTO Subtemas VALUES ('Lavado de Dinero',120,9)
INSERT INTO Subtemas VALUES ('Tasas Promedios A 2097 - SIN USO 2024',121,9)
INSERT INTO Subtemas VALUES ('Cierre de Dia',122,9)
INSERT INTO Subtemas VALUES ('Vuelcos',123,9)
INSERT INTO Subtemas VALUES ('Actualización Manual ODS',124,9)
INSERT INTO Subtemas VALUES ('ABM Grupos de Información',125,9)
INSERT INTO Subtemas VALUES ('Inventario ODS',126,9)
INSERT INTO Subtemas VALUES ('Panel de Conciliación',127,9)
INSERT INTO Subtemas VALUES ('Vuelcos de Archivos emitidos por BCRA',128,9)
INSERT INTO Subtemas VALUES ('Situación del Cliente',129,9)
INSERT INTO Subtemas VALUES ('Inspección BCRA',130,9)
INSERT INTO Subtemas VALUES ('Garantías',131,9)
INSERT INTO Subtemas VALUES ('Situacion',132,9)
INSERT INTO Subtemas VALUES ('Prevision',133,9)
INSERT INTO Subtemas VALUES ('Activos Inmovilizados',134,9)
INSERT INTO Subtemas VALUES ('Operaciones de Cambio',135,9)
INSERT INTO Subtemas VALUES ('Posición Global Neta Moneda Extranjera',136,9)
INSERT INTO Subtemas VALUES ('Reg. Supervisión Trimestral',137,9)
INSERT INTO Subtemas VALUES ('Estado de Situaciones de Deudores',138,9)
INSERT INTO Subtemas VALUES ('Graduación y Fraccionamiento',139,9)
INSERT INTO Subtemas VALUES ('Cuadros SISCEN',140,9)
INSERT INTO Subtemas VALUES ('Ratio de cobertura de Liquidez - SIN USO 2024',141,9)
INSERT INTO Subtemas VALUES ('Grandes Exposiciones al Riesgo de Credito',142,9)
INSERT INTO Subtemas VALUES ('Herramientas de Seguimiento de Liquidez - SIN USO 2024',143,9)
INSERT INTO Subtemas VALUES ('MIPYME ',144,9)
INSERT INTO Subtemas VALUES ('Componente JAVA Gendoc',145,10)
INSERT INTO Subtemas VALUES ('API Generador de Notas .NET',146,10)
INSERT INTO Subtemas VALUES ('Armado de sp recuperadores',147,10)
INSERT INTO Subtemas VALUES ('Gestion y Armado de Notas ',148,10)
INSERT INTO Subtemas VALUES ('Escenarios de Notas ',149,10)
INSERT INTO Subtemas VALUES ('Generacion de notas en PDF',150,10)
INSERT INTO Subtemas VALUES ('Parametrización Concepto y Subconcepto / Equivalencia de Trx',151,11)
INSERT INTO Subtemas VALUES ('Procesos Especiales',152,11)
INSERT INTO Subtemas VALUES ('Pago Haberes / Acreditacion Sueldo',153,11)
INSERT INTO Subtemas VALUES ('Mutuales',154,11)
INSERT INTO Subtemas VALUES ('Impuestos',155,11)
INSERT INTO Subtemas VALUES ('Transferencias Inmediatas',156,11)
INSERT INTO Subtemas VALUES ('Circuito para la Imputación de Lotes',157,11)
INSERT INTO Subtemas VALUES ('Transferencias múltiples',158,11)
INSERT INTO Subtemas VALUES ('Interacción con la cámara BEE',159,11)
INSERT INTO Subtemas VALUES ('Gestión de doc electrónicos',160,11)
INSERT INTO Subtemas VALUES ('Ingresos masivos: Individual CC/CA',161,11)
INSERT INTO Subtemas VALUES ('Ingresos masivos: Individual CR',162,11)
INSERT INTO Subtemas VALUES ('Ingresos masivos: Masivo CA/CC bse',163,11)
INSERT INTO Subtemas VALUES ('Ingresos masivos: Masivo x cliente CA/CC bse',164,11)
INSERT INTO Subtemas VALUES ('Ingresos masivos: Masivo Multihilo CA/CC Piano',165,11)
INSERT INTO Subtemas VALUES ('Parametrización H2H',166,12)
INSERT INTO Subtemas VALUES ('Circuito Operativo – Refresh Dia Abierto / Dia Cerrado',167,12)
INSERT INTO Subtemas VALUES ('Swich/GPL – Intemediarios entre Monitores y Link',168,12)
INSERT INTO Subtemas VALUES ('Conciliación Version Vieja y Nueva',169,12)
INSERT INTO Subtemas VALUES ('Créditos por H2H',170,12)
INSERT INTO Subtemas VALUES ('Plazos fijos por H2H',171,12)
INSERT INTO Subtemas VALUES ('PF precancelables (pesos/uva)',172,12)
INSERT INTO Subtemas VALUES ('Tratamiento de Mensajes H2H',173,12)
INSERT INTO Subtemas VALUES ('SAF – 7*24 -BMR-VOII y CMF',174,12)
INSERT INTO Subtemas VALUES ('Extract - Refresh',175,12)
INSERT INTO Subtemas VALUES ('Extract / sin uso del COBOL CMF',176,12)
INSERT INTO Subtemas VALUES ('Banca Empresa',177,12)
INSERT INTO Subtemas VALUES ('Transferencia 3.0',178,12)
INSERT INTO Subtemas VALUES ('Conciliacion MasterDebit',179,12)
INSERT INTO Subtemas VALUES ('Refresh de Alta de Cuentas Sueldo',180,12)
INSERT INTO Subtemas VALUES ('Refresh de Prestamos y Cuotas',181,12)
INSERT INTO Subtemas VALUES ('Refresh de Movimientos Diferidos',182,12)
INSERT INTO Subtemas VALUES ('Refresh de Cheques Descontados',183,12)
INSERT INTO Subtemas VALUES ('Refresh de Responsables de Cuenta',184,12)
INSERT INTO Subtemas VALUES ('Refresh de Posición Consolidada',185,12)
INSERT INTO Subtemas VALUES ('Refresh de Plazo Fijo',186,12)
INSERT INTO Subtemas VALUES ('Refresh de Saldos',187,12)
INSERT INTO Subtemas VALUES ('Refresh de Movimientos',188,12)
INSERT INTO Subtemas VALUES ('Refresh de los 10 ultimos Movimientos',189,12)
INSERT INTO Subtemas VALUES ('Refresh de CBU',190,12)
INSERT INTO Subtemas VALUES ('Carga de Extract',191,12)
INSERT INTO Subtemas VALUES ('Refresh BEE',192,12)
INSERT INTO Subtemas VALUES ('Refresh cheques cámara',193,12)
INSERT INTO Subtemas VALUES ('Extract novedades e-cheq',194,12)
INSERT INTO Subtemas VALUES ('Extract BEE ',195,12)
INSERT INTO Subtemas VALUES ('Refresh Ordenes Transferencias BEE',196,12)
INSERT INTO Subtemas VALUES ('Refresh consentimiento',197,12)
INSERT INTO Subtemas VALUES ('Servicio Dispara Transaccion usado por CiberBank',198,12)
INSERT INTO Subtemas VALUES ('Adm Usuarios ',199,13)
INSERT INTO Subtemas VALUES ('Login',407,13)
INSERT INTO Subtemas VALUES ('Active Directory BMR',200,13)
INSERT INTO Subtemas VALUES ('Seguridad Centralizada BMR',201,13)
INSERT INTO Subtemas VALUES ('Seguridad Centralizada PIANO',202,13)
INSERT INTO Subtemas VALUES ('Tareas Perfiles',203,13)
INSERT INTO Subtemas VALUES ('Tareas englobadoras – CMF – MB – BSE',204,13)
INSERT INTO Subtemas VALUES ('Controles de Tareas / Supervisión',205,13)
INSERT INTO Subtemas VALUES ('Configuracion de Seguridad de los Archivos',206,13)
INSERT INTO Subtemas VALUES ('Circuito de Vuelco y Administración ',207,14)
INSERT INTO Subtemas VALUES ('Modalidades Parametrización',208,14)
INSERT INTO Subtemas VALUES ('Asignación Universal',209,14)
INSERT INTO Subtemas VALUES ('Nueva Acreditación Anticipada',210,14)
INSERT INTO Subtemas VALUES ('Modalización de Cuentas',211,14)
INSERT INTO Subtemas VALUES ('Acreditación ANSES',212,14)
INSERT INTO Subtemas VALUES ('Funciones Transacciones',213,14)
INSERT INTO Subtemas VALUES ('Proceso Modificación – Migración de Sucursales',214,14)
INSERT INTO Subtemas VALUES ('Rendición y Devolución Anses',215,14)
INSERT INTO Subtemas VALUES ('Emisión de Plasticos',216,14)
INSERT INTO Subtemas VALUES ('Adm. Datos Generales',217,15)
INSERT INTO Subtemas VALUES ('Alta de clientes con ejecución de Alertas',218,15)
INSERT INTO Subtemas VALUES ('Autorización de Alta de clientes',219,15)
INSERT INTO Subtemas VALUES ('Mantenimiento de Cuentas (y Altas Especiales)',220,15)
INSERT INTO Subtemas VALUES ('Param. Grupos Afinidad',221,15)
INSERT INTO Subtemas VALUES ('Cliente Único - Proceso de Alta de Cliente Descentralizado',222,15)
INSERT INTO Subtemas VALUES ('Proceso de Unificación Cliente Duplicado – CMF',223,15)
INSERT INTO Subtemas VALUES ('Alertas - Configuración',224,15)
INSERT INTO Subtemas VALUES ('Tramites y Requisitos ',225,15)
INSERT INTO Subtemas VALUES ('MIPYME',226,15)
INSERT INTO Subtemas VALUES ('Adm. Funciones',227,16)
INSERT INTO Subtemas VALUES ('Comprobantes',228,16)
INSERT INTO Subtemas VALUES ('Perfiles de transacciones',229,16)
INSERT INTO Subtemas VALUES ('Direccionamiento de impresión',230,16)
INSERT INTO Subtemas VALUES ('Inter-Sucursales',231,16)
INSERT INTO Subtemas VALUES ('Param. Transacciones',232,16)
INSERT INTO Subtemas VALUES ('Ejecución de Tx',233,16)
INSERT INTO Subtemas VALUES ('Caja de Seguridad BSE',235,17)
INSERT INTO Subtemas VALUES ('Cajas de Seguridad CMF',236,17)
INSERT INTO Subtemas VALUES ('Administración de Puestos',237,17)
INSERT INTO Subtemas VALUES ('Consulta de Información',238,17)
INSERT INTO Subtemas VALUES ('Parámetros',239,17)
INSERT INTO Subtemas VALUES ('Romaneo',240,17)
INSERT INTO Subtemas VALUES ('Cierre de Tesorería',241,17)
INSERT INTO Subtemas VALUES ('Parametrización de Planillas',242,18)
INSERT INTO Subtemas VALUES ('Ejecución de Plantillas',243,18)
INSERT INTO Subtemas VALUES ('Funciones',244,18)
INSERT INTO Subtemas VALUES ('Web Service de Seguros',245,19)
INSERT INTO Subtemas VALUES ('Planes de Financiación',246,19)
INSERT INTO Subtemas VALUES ('Consultas externas a Nosis',247,19)
INSERT INTO Subtemas VALUES ('Riesgo Crediticio',248,19)
INSERT INTO Subtemas VALUES ('Generador de Pedidos',249,19)
INSERT INTO Subtemas VALUES ('Operatoria Minorista Prendaria (Circuito Minorista)',250,19)
INSERT INTO Subtemas VALUES ('Operatoria Minorista Leasing',251,19)
INSERT INTO Subtemas VALUES ('Desvío de Fondos',252,19)
INSERT INTO Subtemas VALUES ('Circuito de Conformación de Operaciones',253,19)
INSERT INTO Subtemas VALUES ('Administración de garantías',254,19)
INSERT INTO Subtemas VALUES ('Web Service',255,19)
INSERT INTO Subtemas VALUES ('Administración de Requisitos',256,19)
INSERT INTO Subtemas VALUES ('Estructura Atipicas ',257,19)
INSERT INTO Subtemas VALUES ('Solicitud Única',258,19)
INSERT INTO Subtemas VALUES ('Funciones de Pago Especial',408,19)
INSERT INTO Subtemas VALUES ('Aplicacion de Pago Flota ',409,19)
INSERT INTO Subtemas VALUES ('Proceso de Diferimiento de Cuotas',259,19)
INSERT INTO Subtemas VALUES ('IVA',260,20)
INSERT INTO Subtemas VALUES ('Impuesto a los débitos Créditos',261,20)
INSERT INTO Subtemas VALUES ('Ingresos Brutos',262,20)
INSERT INTO Subtemas VALUES ('Sellado',263,20)
INSERT INTO Subtemas VALUES ('SITER',264,20)
INSERT INTO Subtemas VALUES ('SIRCREB',265,20)
INSERT INTO Subtemas VALUES ('CABA',266,20)
INSERT INTO Subtemas VALUES ('Proceso de Conciliacion contable IVA – BMR',267,20)
INSERT INTO Subtemas VALUES ('Excencion de Impuestos',268,20)
INSERT INTO Subtemas VALUES ('Circuito BSE',269,21)
INSERT INTO Subtemas VALUES ('Circuito BMR',270,21)
INSERT INTO Subtemas VALUES ('Panel de causa',271,21)
INSERT INTO Subtemas VALUES ('Activar cuentas',272,21)
INSERT INTO Subtemas VALUES ('Gestión Instrumentos Judiciales',273,21)
INSERT INTO Subtemas VALUES ('Autorización de instrumentos Judiciales',274,21)
INSERT INTO Subtemas VALUES ('Consulta de movimientos por Cuentas',275,21)
INSERT INTO Subtemas VALUES ('Consulta Información de cuentas',276,21)
INSERT INTO Subtemas VALUES ('Cierre de Cuentas Judiciales',277,21)
INSERT INTO Subtemas VALUES ('Mantenimiento de chequeras',278,21)
INSERT INTO Subtemas VALUES ('Informes Generales',279,21)
INSERT INTO Subtemas VALUES ('Consulta de movimientos',280,21)
INSERT INTO Subtemas VALUES ('Administración Manual de Obleas Judiciales',281,21)
INSERT INTO Subtemas VALUES ('Configuración de Destinos',282,21)
INSERT INTO Subtemas VALUES ('Listado de Obleas',283,21)
INSERT INTO Subtemas VALUES ('Web Judiciales - Metacomandos',284,21)
INSERT INTO Subtemas VALUES ('Configuración de Concesionarios',285,22)
INSERT INTO Subtemas VALUES ('Configuración de Modelos',286,22)
INSERT INTO Subtemas VALUES ('Configuración de Concesionarios – Modelos',287,22)
INSERT INTO Subtemas VALUES ('Configuración de Productos Financieros',288,22)
INSERT INTO Subtemas VALUES ('Liquidación Floorpán',289,22)
INSERT INTO Subtemas VALUES ('Administración de Garantías',290,22)
INSERT INTO Subtemas VALUES ('Administración de Certificados',291,22)
INSERT INTO Subtemas VALUES ('Deuda de Fábrica',292,22)
INSERT INTO Subtemas VALUES ('Riesgo Crediticio',293,22)
INSERT INTO Subtemas VALUES ('Generación de Disponible',294,22)
INSERT INTO Subtemas VALUES ('Segmentación para la Gestión de Cobranza',295,23)
INSERT INTO Subtemas VALUES ('Definición de Campañas',296,23)
INSERT INTO Subtemas VALUES ('Ejecución de Campañas ',297,23)
INSERT INTO Subtemas VALUES ('Circuito CMF',298,24)
INSERT INTO Subtemas VALUES ('Circuito BMR – Bussiness Suite',299,24)
INSERT INTO Subtemas VALUES ('Circuito Mercedes',300,24)
INSERT INTO Subtemas VALUES ('Circuito CMF',301,25)
INSERT INTO Subtemas VALUES ('Circuito BSE',302,25)
INSERT INTO Subtemas VALUES ('Circuito BMR',303,25)
INSERT INTO Subtemas VALUES ('Metacomandos',304,26)
INSERT INTO Subtemas VALUES ('Frame',305,26)
INSERT INTO Subtemas VALUES ('Interbanking / Gateway',306,26)
INSERT INTO Subtemas VALUES ('APIs',410,26)
INSERT INTO Subtemas VALUES ('Automatizacion de cierre ',307,26)
INSERT INTO Subtemas VALUES ('Circuito y Ventana Especial BSE',308,27)
INSERT INTO Subtemas VALUES ('Circuito',309,28)
INSERT INTO Subtemas VALUES ('Generador de Pedidos',310,28)
INSERT INTO Subtemas VALUES ('Normativa del BCRA referida a Transferencias',311,29)
INSERT INTO Subtemas VALUES ('Productos de transferencias',312,29)
INSERT INTO Subtemas VALUES ('Tipos de transferencias',313,29)
INSERT INTO Subtemas VALUES ('Instancias',314,29)
INSERT INTO Subtemas VALUES ('Procesos',315,29)
INSERT INTO Subtemas VALUES ('Tareas',316,29)
INSERT INTO Subtemas VALUES ('Funciones de las transacciones ',317,29)
INSERT INTO Subtemas VALUES ('Reportes de control',318,29)
INSERT INTO Subtemas VALUES ('Contabilización',319,29)
INSERT INTO Subtemas VALUES ('Estructura archivos NACHA',320,29)
INSERT INTO Subtemas VALUES ('Normativa del BCRA referida a Débitos Directos',321,30)
INSERT INTO Subtemas VALUES ('Circuitos Ordenante-Receptor',322,30)
INSERT INTO Subtemas VALUES ('Tipos de mensajes',323,30)
INSERT INTO Subtemas VALUES ('Instancias',324,30)
INSERT INTO Subtemas VALUES ('Procesos',325,30)
INSERT INTO Subtemas VALUES ('Tareas',326,30)
INSERT INTO Subtemas VALUES ('Funciones de las transacciones ',327,30)
INSERT INTO Subtemas VALUES ('Configuración de accesorios de las transacciones',328,30)
INSERT INTO Subtemas VALUES ('Relación con el modulo cobro de servicios',329,30)
INSERT INTO Subtemas VALUES ('Estructura archivos NACHA',330,30)
INSERT INTO Subtemas VALUES ('Esquemas de Multiples Vtos y Reintentos -',331,30)
INSERT INTO Subtemas VALUES ('Parametrización',332,31)
INSERT INTO Subtemas VALUES ('Segmentación',333,31)
INSERT INTO Subtemas VALUES ('Costo Amortizado',334,31)
INSERT INTO Subtemas VALUES ('Valor Razonable',335,31)
INSERT INTO Subtemas VALUES ('Pérdida Esperada',336,31)
INSERT INTO Subtemas VALUES ('Modificaciones a pérdida esperada',337,31)
INSERT INTO Subtemas VALUES ('Ajuste UVA Creditos',338,32)
INSERT INTO Subtemas VALUES ('Ajuste UVA Pasivas',339,32)
INSERT INTO Subtemas VALUES ('Ajuste de Cartera Multihilo',340,33)
INSERT INTO Subtemas VALUES ('Imputación de Lotes',341,33)
INSERT INTO Subtemas VALUES ('Proceso de Devengamiento',342,33)
INSERT INTO Subtemas VALUES ('Agente multihilo programación .NET',343,33)
INSERT INTO Subtemas VALUES ('Agente MultiHilo',344,33)
INSERT INTO Subtemas VALUES ('Administrador de Socios',345,34)
INSERT INTO Subtemas VALUES ('Resúmenes de cuenta',346,34)
INSERT INTO Subtemas VALUES ('Cobranzas x caja',347,34)
INSERT INTO Subtemas VALUES ('Cobranzas externas',348,34)
INSERT INTO Subtemas VALUES ('Administrador de Comercios',349,34)
INSERT INTO Subtemas VALUES ('Liquidación de Comercio',350,34)
INSERT INTO Subtemas VALUES ('Generación de Resúmenes en PDF',351,34)
INSERT INTO Subtemas VALUES ('Envio de resumen por Mail',352,34)
INSERT INTO Subtemas VALUES ('Administración de Novedades',353,34)
INSERT INTO Subtemas VALUES ('Implementacion en cierre - Ajuste de cartera',354,35)
INSERT INTO Subtemas VALUES ('Implementacion en cierre - Devengamiento',355,35)
INSERT INTO Subtemas VALUES ('Envio de mails ',356,35)
INSERT INTO Subtemas VALUES ('Copia de Archivos automaticos',357,35)
INSERT INTO Subtemas VALUES ('Componente internos del Agente 7x24',358,35)
INSERT INTO Subtemas VALUES ('Novedades Link alta/baja Cuenta (echeq)',359,35)
INSERT INTO Subtemas VALUES ('comoponentes internos de Report server',360,36)
INSERT INTO Subtemas VALUES ('Implementacion de reportes',361,36)
INSERT INTO Subtemas VALUES ('Capacitación Funcional Básica - Jorge Márquez',362,37)
INSERT INTO Subtemas VALUES ('Capacitación Herramientas Apis',363,37)
INSERT INTO Subtemas VALUES ('Circuitos Prestamos Mantenimiento',364,37)
INSERT INTO Subtemas VALUES ('Capacitación H2H',365,37)
INSERT INTO Subtemas VALUES ('Capacitación Multihilos',366,37)
INSERT INTO Subtemas VALUES ('Induccion Qc',367,37)
INSERT INTO Subtemas VALUES ('Induccion IBS PB SYBASE',368,37)
INSERT INTO Subtemas VALUES ('Induccion_IBS_PB_SYBASE_2020_Matias_Diaz_Linares',369,37)
INSERT INTO Subtemas VALUES ('Capacitación SYBASE POWER BUILDER - Julio Leiva',370,37)
INSERT INTO Subtemas VALUES ('Capacitación NIIF - César Romano',371,37)
INSERT INTO Subtemas VALUES ('Capacitación NIIF - Hernán Honorato',372,37)
INSERT INTO Subtemas VALUES ('Formación Débito Directo - Víctor Giampaoli',373,37)
INSERT INTO Subtemas VALUES ('Formación Débito Directo - Ana Paula Pelegrina y Javier Ocaranza',374,37)
INSERT INTO Subtemas VALUES ('Sistema de amortizaciones de cuotas - Hernán Honorato',375,37)
INSERT INTO Subtemas VALUES ('Capacitación Contable Básica',376,37)
INSERT INTO Subtemas VALUES ('Tasa de interés',377,37)
INSERT INTO Subtemas VALUES ('Postman',378,37)
INSERT INTO Subtemas VALUES ('Modulo Contable (Funcional y Técnico de IBS)',379,37)
INSERT INTO Subtemas VALUES ('Automatización de APIS',380,37)
INSERT INTO Subtemas VALUES ('Automatización FrontEnd (WEB)',381,37)
INSERT INTO Subtemas VALUES ('Generador de Apis (GENSOA)',382,38)
INSERT INTO Subtemas VALUES ('Licencias para uso de Apis',383,38)
INSERT INTO Subtemas VALUES ('Token',384,38)
INSERT INTO Subtemas VALUES ('Frame',385,38)
INSERT INTO Subtemas VALUES ('Sucursal Digital - Banca Individuo (WEB)',386,38)
INSERT INTO Subtemas VALUES ('Sucursal Digital - Banca Empresa (WEB)',387,38)
INSERT INTO Subtemas VALUES ('Sucursal Digital - Banca Individuo (Mobile)',388,38)
INSERT INTO Subtemas VALUES ('Sucursal Digital - Banca Empresa (Mobile)',389,38)
INSERT INTO Subtemas VALUES ('BackOffice - Mesa de Ayuda',390,38)
INSERT INTO Subtemas VALUES ('BackOffice - Comercial',391,38)
INSERT INTO Subtemas VALUES ('BackOffice - IT',392,38)
INSERT INTO Subtemas VALUES ('ASE',393,39)
INSERT INTO Subtemas VALUES ('Pasajes',394,39)
INSERT INTO Subtemas VALUES ('GOOGS (controlador de versiones)',395,39)
INSERT INTO Subtemas VALUES ('SICP WEB',396,39)
INSERT INTO Subtemas VALUES ('SAPYA',397,39)
INSERT INTO Subtemas VALUES ('TranServer',398,39)
INSERT INTO Subtemas VALUES ('Power Designer',399,39)
INSERT INTO Subtemas VALUES ('Adm_Frame',400,39)
INSERT INTO Subtemas VALUES ('Despachante H2H',401,39)
INSERT INTO Subtemas VALUES ('SOAP UI',402,39)
INSERT INTO Subtemas VALUES ('JMETER',403,39)
INSERT INTO Subtemas VALUES ('Selenium',404,39)
INSERT INTO Subtemas VALUES ('Postman',405,39)
INSERT INTO Subtemas VALUES ('Python',406,39)
INSERT INTO Subtemas VALUES ('Administracion de Productos',101,1)
